// Real Chromium exercise. Creates disposable data and never touches your memorials.
import {spawn, execFileSync} from 'node:child_process';
import {mkdtemp, rm, mkdir, writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join, resolve} from 'node:path';
import assert from 'node:assert/strict';
const root=resolve('remembrance');
const tmp=await mkdtemp(join(tmpdir(),'remembrance-browser-'));
const env={...process.env,REMEMBRANCE_DATA:join(tmp,'data'),PUBLIC_URL:'http://127.0.0.1:8788',REMEMBRANCE_SECURE:'0',TRUST_PROXY:'0'};
const python=join(root,'.venv/bin/python');
execFileSync(python,['-m','flask','--app','app','seed-demo'],{cwd:root,env});
const server=spawn(python,['-m','flask','--app','app','run','--host','127.0.0.1','--port','8788'],{cwd:root,env,stdio:'ignore'});
const chrome=spawn('chromium',['--headless','--no-sandbox','--disable-gpu','--remote-debugging-port=9224',`--user-data-dir=${join(tmp,'chrome')}`,'about:blank'],{stdio:'ignore'});
let ws;
try{
  let tabs;
  for(let i=0;i<100;i++){
    try{await fetch(env.PUBLIC_URL+'/healthz');tabs=await(await fetch('http://127.0.0.1:9224/json')).json();break;}catch{await new Promise(r=>setTimeout(r,100));}
  }
  assert.ok(tabs,'Server and Chromium must start');
  ws=new WebSocket(tabs.find(t=>t.type==='page').webSocketDebuggerUrl);
  await new Promise((ok,no)=>{ws.onopen=ok;ws.onerror=no;});
  let id=0;const pending=new Map();const errors=[];
  ws.onmessage=e=>{const msg=JSON.parse(e.data);if(msg.method==='Runtime.exceptionThrown')errors.push(msg.params.exceptionDetails);if(pending.has(msg.id)){const [ok,no]=pending.get(msg.id);pending.delete(msg.id);msg.error?no(Error(msg.error.message)):ok(msg.result);}};
  const call=(method,params={})=>new Promise((ok,no)=>{const key=++id;pending.set(key,[ok,no]);ws.send(JSON.stringify({id:key,method,params}));});
  const evaluate=async expression=>{const r=await call('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
  const until=async expr=>{for(let i=0;i<100;i++){if(await evaluate(expr))return;await new Promise(r=>setTimeout(r,100));}throw Error(`Timed out: ${expr}; ${await evaluate('document.body.innerText')}`);};
  const go=async path=>{await call('Page.navigate',{url:env.PUBLIC_URL+path});await until(`document.readyState==='complete' && location.pathname===${JSON.stringify(path)}`);};
  const fill=async values=>evaluate(`(()=>{const values=${JSON.stringify(values)};for(const [name,value] of Object.entries(values)){const el=document.querySelector('[name="'+name+'"]');if(el.type==='checkbox')el.checked=value;else el.value=value;}return true;})()`);
  const screenshot=async file=>{const r=await call('Page.captureScreenshot',{format:'png',captureBeyondViewport:true});await writeFile(join(root,'dist',file),Buffer.from(r.data,'base64'));};
  await mkdir(join(root,'dist'),{recursive:true});
  await call('Page.enable');await call('Runtime.enable');
  await call('Emulation.setDeviceMetricsOverride',{width:1440,height:1000,deviceScaleFactor:1,mobile:false});
  await go('/');
  assert.match(await evaluate('document.body.innerText'),/A life, remembered/);
  await screenshot('home-desktop.png');
  await go('/m/eleanor-example');
  assert.match(await evaluate('document.body.innerText'),/Eleanor Rose Bennett/);
  assert.equal(await evaluate('document.querySelectorAll(".timeline article").length'),4);
  await screenshot('memorial-desktop.png');
  await call('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
  assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true,'Memorial mobile layout must not overflow');
  await screenshot('memorial-mobile.png');
  await go('/');
  assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true,'Home mobile layout must not overflow');
  await screenshot('home-mobile.png');
  await go('/register');
  await fill({name:'Browser Tester',email:'browser@example.com',password:'browser test passphrase',terms:true});
  await evaluate('document.querySelector(".form-stack").requestSubmit()');
  await until("location.pathname==='/dashboard' && document.body.innerText.includes('Held close.')");
  await go('/memorials/new');
  await fill({name:'Browser Memorial',born:'1940-01-02',died:'2024-01-02',biography:'A browser-tested life story.',authority:'executor',authority_name:'Browser Tester',consent:true,visibility:'public'});
  await evaluate('document.querySelector(".form-stack").requestSubmit()');
  await until("location.pathname.endsWith('/manage') && document.body.innerText.includes('Add a memory.')");
  const base=await evaluate("location.pathname.replace('/manage','')");
  assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true,'Dashboard mobile layout must not overflow');
  await screenshot('manage-mobile.png');
  await evaluate(`(()=>{const f=document.querySelector('form[action$="/events"]');f.querySelector('[name=year]').value='1965';f.querySelector('[name=title]').value='A browser chapter';f.querySelector('[name=story]').value='Remembered with love.';f.requestSubmit();})()`);
  await until("document.body.innerText.includes('1965 · A browser chapter')");
  await go(base);
  await evaluate(`(()=>{const f=document.querySelector('form[action$="/tributes"]');f.querySelector('[name=name]').value='A friend';f.querySelector('[name=body]').value='A browser tribute.';f.querySelector('[name=consent]').checked=true;f.requestSubmit();})()`);
  await until("document.body.innerText.includes('Thank you for remembering.')");
  await go(base);
  assert.equal(await evaluate("document.body.innerText.includes('A browser tribute.')"),false);
  await go(base+'/manage');
  await evaluate("document.querySelector('button[value=approved]').click()");
  await until("document.body.innerText.includes('The tribute has been approved.')");
  await go(base);
  assert.equal(await evaluate("document.body.innerText.includes('A browser tribute.')"),true);
  await evaluate("document.querySelector('form[action$=\"/candle\"] button').click()");
  await until("document.body.innerText.includes('A candle is lit')");
  await go(base+'/plaque');
  assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true,'Plaque mobile layout must not overflow');
  assert.equal(await evaluate("document.querySelector('.plaque img').naturalWidth>0"),true);
  await go('/install');
  await until("!!navigator.serviceWorker.controller");
  const cacheKeys=await evaluate("(async()=>{const paths=[];for(const key of await caches.keys()){const cache=await caches.open(key);for(const req of await cache.keys())paths.push(new URL(req.url).pathname);}return paths;})()");
  assert.ok(cacheKeys.flat().every(x=>x.startsWith('/static/')),'Private pages must never enter offline caches');
  await call('Network.enable');
  await call('Network.emulateNetworkConditions',{offline:true,latency:0,downloadThroughput:0,uploadThroughput:0});
  await call('Page.navigate',{url:env.PUBLIC_URL+'/dashboard'});
  await until("document.body.innerText.includes('A quiet pause.')");
  assert.deepEqual(errors,[],'No browser script errors');
  console.log('PASS: desktop/mobile layouts, registration, memorial creation, timeline, tribute moderation, candle, QR, install shell, and offline privacy. Screenshots in remembrance/dist/.');
}finally{
  ws?.close();chrome.kill();server.kill();
  await Promise.all([new Promise(r=>chrome.once('exit',r)),new Promise(r=>server.once('exit',r))]);
  await rm(tmp,{recursive:true,force:true});
}
